# Podman/Docker-compatible build file (standard Dockerfile syntax).
#   podman build -t polardrl -f Containerfile .   (Fedora default — no Docker Engine needed)
#   docker build -t polardrl .                    (works identically on Docker if a teammate uses it)
FROM python:3.11-slim

WORKDIR /app

# curl/unzip/bzip2 are needed by datasets/download.sh (fetches Dolphins/
# Netscience from KONECT as .tar.bz2, Diseasome from networkrepository.com
# as .zip, GrQc from SNAP as .gz); tar and gunzip are already in the base
# image's coreutils/gzip.
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl unzip bzip2 \
    && rm -rf /var/lib/apt/lists/*

# uv gives fast, reproducible installs from pyproject.toml
RUN pip install --no-cache-dir uv

COPY pyproject.toml ./
COPY src/ ./src/
COPY tests/ ./tests/
COPY scripts/ ./scripts/
COPY datasets/download.sh ./datasets/download.sh
COPY paper_results/ ./paper_results/

# Editable install (-e): datasets.py resolves DATASETS_ROOT relative to its
# own __file__, assuming the package lives under <repo_root>/src/polardrl --
# true locally (README's `uv pip install -e .`) and only true in the image
# if the install stays editable too. A non-editable install copies the
# package into site-packages, breaking that relative path (it would look
# for datasets under /usr/local/lib instead of /app).
RUN uv pip install --system -e .

# datasets/raw (fetched by datasets/download.sh, network access required) and
# results/ (generated by scripts/reproduce_*.py) are gitignored and NOT baked
# into the image -- mount them as volumes so downloaded data and reproduction
# outputs persist across container runs instead of being re-fetched/lost each
# time. See README.md "Container usage" for the podman run invocation.
VOLUME ["/app/datasets/raw", "/app/results"]

# Default: run the test suite as an image smoke test (everything except
# datasets/raw-dependent tests, which need datasets/download.sh run first
# via a mounted volume -- see README.md for the full reproduction workflow).
CMD ["pytest", "-v"]
